### ISSUE TITLE
not working on 2.93

### ISSUE THREAD

**Issue by visualworx** [BlenderHQ/path_tool#1]
Hello there,

Thanks for the great addon. This is a must for blender users. 

BTW, it's not working with ver. 2.93. Please see below.

![image](https://user-images.githubusercontent.com/54339099/122046605-157e4380-ce1a-11eb-8706-e45f7b1782a3.png)

Thanks,
Sean

**Comment by ivan-perevala** [comment]
Resolved.
Commit is small, I see no reason to separate new release for new Blender version, so I just added small versioning switch for Blender v2.93+ [Commit Link Here](https://github.com/BlenderHQ/path_tool/commit/30608af972129fb98858f737263c1a4d2af056c5)

Thank you for feedback!)
